### ISSUE TITLE
Usage with Gnome 3.20 

### ISSUE THREAD

**Issue by s373r** [arjan/gnome-shell-go-to-last-workspace#5]
If you by some reason need run this awesome extension on ancient Gnome 3.20, e.g. on Ubuntu 16.04, please use the following instructions:

**0)** Go to your user local extension directory:
`$ cd ~/.local/share/gnome-shell/extensions`

**1)** Remove the extension if it exists:
`$ rm -rf ./gnome-shell-go-to-last-workspace@github.com/`

**2)** Clone source code:
`$ git clone https://github.com/arjan/gnome-shell-go-to-last-workspace.git`

**3)** Rename the cloned repo to correspond the extension UUID:
`$ mv gnome-shell-go-to-last-workspace gnome-shell-go-to-last-workspace@github.com`

**4)** Pick an old working revision:
`$  git checkout 6c82ffa82b869e6a97928709788f9a68b38369fa`

**5)** Set the default hotkey:
`$ gsettings --schemadir ~/.local/share/gnome-shell/extensions/gnome-shell-go-to-last-workspace@github.com/schemas set org.gnome.shell.extensions.go-to-last-workspace shortcut-key "['<Super>escape']"`

**6)** Restart Gnome Shell:
Press `Alt+F2`, then type `r` and press `enter` key

Done! Hooray!

---

@arjan, 

**1)** could you please add it to a wiki (you need to create it first) of this Github repo?
Or, 
**2)** I can make a PR w/ changes to README if that works.

What do you think which variant (**1)** or **2)**) is better?

**Comment by arjan** [comment]
Added this to the readme, thanks!
