### ISSUE TITLE
Using with Gnome 3.36

### ISSUE THREAD

**Issue by peey** [arjan/gnome-shell-go-to-last-workspace#6]
I'm wondering if you've tested if this works with Gnome 3.36 (ubuntu 20.04)

I tried it but it doesn't seem to work

**Comment by arjan** [comment]
Yes, I am running 3.36 as well. Although not listed in the version metadata, it just works for me.

**Comment by peey** [comment]
Do you have any suggestions for debugging this?

1. Do I need to restart my gnome session after installing for this to work (I restarted my whole device but not sure if that was necessary)
2. Could I trigger this programmatically? I thought that there may be a keybinding conflict but I tried to change the default keybinding. Is there a way I could trigger the switching from command line to see if that's the issue?

I've installed from gnome extensions page

**Comment by arjan** [comment]
Works now
